services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_etl:
    image: postgres:15
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
      POSTGRES_DB: etl_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_etl_data:/var/lib/postgresql/data
    restart: always

  airflow-webserver:
    image: apache/airflow:2.9.0
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__RBAC: "True"
      AIRFLOW__WEBSERVER__SECRET_KEY: "e076383dbb8d9340d31c4e74d51f9e9dd9959557c31abba7ae5b2445be17e105"
      AIRFLOW__CORE__FERNET_KEY: "e076383dbb8d9340d31c4e74d51f9e9dd9959557c31abba7ae5b2445be17e105"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.0
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "e076383dbb8d9340d31c4e74d51f9e9dd9959557c31abba7ae5b2445be17e105"
      AIRFLOW__CORE__FERNET_KEY: "e076383dbb8d9340d31c4e74d51f9e9dd9959557c31abba7ae5b2445be17e105"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    command: scheduler

volumes:
  postgres_data:
  postgres_etl_data:
